name: "Get Current Time"
author: "Gerred Dillon <hello@gerred.org>, Shahar Frank <srfrnk@gmail.com>, Joshua Chan <josStorer@outlook.com>"
description: "Get the current time with format and utcOffset"
branding:
  icon: clock
  color: blue
inputs:
  format:
    description: "Time format to use using [MomemtJS format syntax](https://momentjs.com/docs/#/displaying/format/)"
    required: false
  utcOffset:
    description: "UTC time offset to use using [MomemtJS utcOffset syntax](https://momentjs.com/docs/#/manipulating/utc-offset/)"
    required: false
outputs:
  time:
    description: "The time this action was run"
  formattedTime:
    description: "The time this action was run - formatted using `format` and `utcOffset` input"
runs:
  using: "node12"
  main: "dist/index.js"
